language: python
dist: xenial
sudo: true

python:
  - 3.9

services:
  - postgresql
addons:
  postgresql: '9.5'
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - CODECOV_TOKEN='6d711f6b-d1fc-4070-99aa-cab8ab0572f4'

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov
