# Generated by Django 3.2.7 on 2021-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_modulo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='order',
            field=models.IntegerField(),
        ),
    ]
