# Generated by Django 3.2.7 on 2021-09-27 18:03

from django.db import migrations
from django.utils.text import slugify


def popular_slug(apps, schema_editor):
    Modulo = apps.get_model('modulos', 'Modulo')
    for modulo in Modulo.objects.all():
        modulo.slug = slugify(modulo.titulo)
        modulo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_alter_modulo_order'),
    ]

    operations = [
        migrations.RunPython(popular_slug)
    ]
