# Generated by Django 3.2.7 on 2021-09-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_aula_vimeo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='vimeo_id',
            field=models.CharField(max_length=32),
        ),
    ]
