# Generated by Django 4.0.4 on 2022-05-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0009_auto_vimeo_obrigatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='order',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
